version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    env_file:
      - back/.env
    volumes:
      - mongo:/data/db

  node:
    container_name: node
    build: ./back
    ports:
      - 5000:5000
    environment:
      MONGO_INITDB_ROOT_USERNAME: master
      MONGO_INITDB_ROOT_PASSWORD: 128547
    depends_on:
      - mongodb
    env_file:
      - ./back/.env

  react:
    container_name: react
    build: ./front
    volumes:
      - react-volume:/var/www/html
    env_file:
      - ./front/.env

  nginx_app:
    container_name: nginx_app
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - react-volume:/var/www/html
    depends_on:
      - mongodb
      - node
      - react

volumes:
  mongo: # volume para os mongo
  react-volume:

